version: "3.9"

services:
  app:
    build: ./app
    restart: always
    container_name: birthday_discord_bot
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pwd
      MYSQL_DATABASE: DiscordbotDB
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "main.py"]
  db:
    image: mysql:8.0
    restart: always
    container_name: bot_database
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pwd
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
